<?php

	include 'conexion.php';
	
	$NOMBRE_DUENO = $_POST['NOMBRE_DUENO'];
	$NOMBRE = $_POST['NOMBRE'];
	$APELLIDO = $_POST['APELLIDO'];
	$TELEFONO = $_POST['TELEFONO'];
	$DOMICILIO = $_POST['DOMICILIO'];
	$CORREO = $_POST['CORREO'];
	$CURP = $_POST['CURP'];
	$RFC = $_POST['RFC'];
	$UNIDAD = $_POST['UNIDAD'];
	$MATRICULA = $_POST['MATRICULA'];
	$COLOR = $_POST['COLOR'];
	
	$connect->query("INSERT INTO independientes (NOMBRE_DUENO,NOMBRE,APELLIDO,TELEFONO,DOMICILIO,CORREO,CURP,RFC,UNIDAD,MATRICULA,COLOR) VALUES ('".$NOMBRE_DUENO."','".$NOMBRE."','".$APELLIDO."','".$TELEFONO."','".$DOMICILIO."','".$CORREO."','".$CURP."','".$RFC."','".$UNIDAD."','".$MATRICULA."','".$COLOR."')")

?>